name: CI Test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run tests on"
        required: true
  push:
    branches: [main, v2]
  pull_request:
    branches: [main, v2]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.inputs.branch || github.head_ref || github.ref_name }}

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run test

      - name: Build package
        run: npm run build
