name: Bump Version and Prepare Release

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: "Select which part of the version to increment"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
      fetch-depth:
        description: "Specify fetch-depth (default: 100)"
        required: false
        default: "100"
      commit-sha:
        description: "Optional: Git commit hash to bump from"
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target commit
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: ${{ github.event.inputs.fetch-depth }}
          fetch-tags: true
          ref: ${{ github.event.inputs.commit-sha != '' && github.event.inputs.commit-sha || 'main' }}

      - name: Set up Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Bump package version (no tag)
        run: npm version ${{ github.event.inputs.bump-type }} --no-git-tag-version

      - name: Update changelog (conventional-changelog)
        run: npm run changelog

      - name: Format project
        run: npm run format

      - name: Set up Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add .
          git commit -m "chore: bump version and update changelog" || echo "No changes to commit"

      - name: Get version from package.json
        id: get_version
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          commit-message: "chore: bump version and update changelog"
          title: "chore: bump version to v${{ steps.get_version.outputs.version }}"
          body: |
            This pull request was generated automatically.

            ### Summary
            - Bumps the version to **v${{ steps.get_version.outputs.version }}**
            - Updates the `changelog.md` using conventional commits

            ### ⚠️ CI Notice
            Due to GitHub Actions limitations, CI does **not run automatically** on this pull request.
            Please manually trigger the CI workflow by following the link below:

            👉 [Run CI manually](https://github.com/${{ github.repository }}/actions/workflows/ci.yml)

            To run CI on this PR:

            1. Copy and paste the following branch name into the input field:
              ```
              auto/bump-${{ github.run_id }}
              ```
            2. Click **"Run workflow"**

            Once CI passes, feel free to review and merge this PR.

            ### Next Step
            Once this PR is merged into `main`, the release workflow will detect the version change and automatically create a tag and publish a release.

            _Triggered by GitHub Actions in response to manual version bump request._
          branch: auto/bump-${{ github.run_id }}
          base: main
