name: Manual Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Existing tag to release (e.g., v1.2.3)"
        required: true
        type: string

permissions:
  contents: write
  id-token: write

jobs:
  manual-release:
    uses: ./.github/workflows/reusable-release.yml
    with:
      tag: ${{ github.event.inputs.tag }}
    secrets: inherit
