name: Bump Version and Prepare Release

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: "Select which part of the version to increment"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
      fetch-depth:
        description: "Specify fetch-depth (default: 100)"
        required: false
        default: "100"
      commit-sha:
        description: "Optional: Git commit hash to bump from"
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target commit
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: ${{ github.event.inputs.fetch-depth }}
          fetch-tags: true
          ref: ${{ github.event.inputs.commit-sha != '' && github.event.inputs.commit-sha || 'main' }}

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Bump package version (no tag)
        run: npm version ${{ github.event.inputs.bump-type }} --no-git-tag-version

      - name: Update changelog (conventional-changelog)
        run: npm run changelog

      - name: Format project
        run: npm run format

      - name: Set up Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add .
          git commit -m "chore: bump version and update changelog" || echo "No changes to commit"

      - name: Get version from package.json
        id: get_version
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          commit-message: "chore: bump version and update changelog"
          title: "chore: bump version to v${{ steps.get_version.outputs.version }}"
          body: |
            This pull request was created automatically.

            ### Summary
            - Updates the version to **v${{ steps.get_version.outputs.version }}**
            - Updates the `changelog.md` using conventional commits

            ### ⚠️ CI Notice
            Due to limitations with `GITHUB_TOKEN`, CI checks may **not run for the first commit** in this pull request.

            If you do not see any CI checks, please run them manually:

            1. Copy this branch name:
              ```
              auto/bump-${{ github.run_id }}
              ```
            2. Go to the CI workflow page:
              👉 [Run CI manually](https://github.com/${{ github.repository }}/actions/workflows/ci.yml)
            3. Keep **"Use workflow from:"** as `main`
            4. Paste the branch name
            5. Click **"Run workflow"**

            ### After Merge
            When this pull request is merged into `main`, the release workflow will make a tag and publish a release automatically.

            _This PR was made by GitHub Actions "a manual version bump request."_
          branch: auto/bump-${{ github.run_id }}
          base: main
