name: Please Bump

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: "Choose version bump type"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  check-version-and-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
          fetch-tags: true

      - name: Set up Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm i

      - name: Bump
        run: npm version ${{ github.event.inputs.bump-type }} --no-git-tag-version

      - name: Changelog
        run: npm run changelog

      - name: Set up Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add .
          git commit -m "Auto-generated changes" || echo "No changes to commit"

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
  
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: auto-update files"
          title: "chore: please bump to ${{ steps.get_version.outputs.version }}"
          body: |
            This PR was created automatically by a GitHub Action.
          branch: auto/pr-${{ github.run_id }}
          base: main
