name: Release to npm

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Existing tag to release (e.g., v1.2.3 or v1.2.3-beta.1)"
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Determine tag
        id: vars
        run: |
          echo "tag=${{ github.event.inputs.tag || github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Validate SemVer format (simple)
        run: |
          TAG="${{ steps.vars.outputs.tag }}"
          if [[ ! "$TAG" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.\-]+)?$ ]]; then
            echo "Invalid SemVer format: $TAG"
            exit 1
          fi
          echo "Valid SemVer: $TAG"

      - name: Check out repository at the specified tag
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.vars.outputs.tag }}
          fetch-depth: 0 # Important for tag-based checkout

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm i

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: |
          if [[ "${TAG}" == *-* ]]; then
            # prerelease: contains a dash
            npm publish --provenance --access public --tag beta
          else
            # regular release
            npm publish --provenance --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          TAG: ${{ steps.vars.outputs.tag }}

      - name: Upload artifacts to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.css
            dist/*.css.map
            dist/checksums.sha256
            dist/checksums.sha384
